### ISSUE TITLE
Breaks icons on Slack

### ISSUE THREAD

**Issue by markasoftware** [tavyandy97/span-tree#31]
Firefox 75 on OpenSUSE Linux. Breaks in all my slack servers. Example: https://sendvid.com/1vg3vmmo

**Comment by floweb** [comment]
I've got the same issue, Firefox 76.0.1 on Windows 10.

**Comment by tavyandy97** [comment]
Hey @markasoftware and @floweb !

The issue has been reproduced and we're working on it. We will be releasing a patch for it very soon. Hope you are finding SpanTree useful!

Thank You for the feedback and please do let me know if you have more.

**Comment by tavyandy97** [comment]
The issue has been resolved and merged. The version(v0.0.2.2) has been given to Chrome Webstore and Mozilla Addons for approval. I will update this issue when the release goes live.

**Comment by vedanshgarg** [comment]
Hi @markasoftware & @floweb, v0.0.2.2 is now live on Mozilla addons.
https://addons.mozilla.org/en-GB/firefox/addon/spantree-gitlab-tree/

**Comment by floweb** [comment]
Solved! Thanks!

**Comment by vedanshgarg** [comment]
v0.0.2.2 is live on Chrome web store as well. Contains minor bug fixes.
