### ISSUE TITLE
Error and react message in console

### ISSUE THREAD

**Issue by Nisgrak** [tavyandy97/span-tree#34]
With the new update it shows this message in the console.

The content.js point to spantree extension.
![image](https://user-images.githubusercontent.com/19597708/82803054-2ad7a700-9e80-11ea-864d-a35249127ede.png)

**Comment by tavyandy97** [comment]
We'll be working on this issue. However it does not affect the working of the extension. Thanks for reporting this issue.

**Comment by vedanshgarg** [comment]
Hi @Nisgrak, this is a known webpack issue ( <= v3.x) https://github.com/reduxjs/redux/issues/2878
