### ISSUE TITLE
CSS file injected on all the web sites

### ISSUE THREAD

**Issue by Mte90** [tavyandy97/span-tree#39]
Looking on my pages I am getting that css file injected in all the website I am visiting from wikipedia to my blog.

**Comment by tavyandy97** [comment]
Hey @Mte90 ! Thanks for reporting the issue. A patch for the above will be released in a week.

**Comment by tavyandy97** [comment]
Hey @Mte90 !
The extension has been updated on the Chrome Webstore and Mozilla Addons to v0.0.2.5 with a fix for issue.

**Comment by Mte90** [comment]
confirmed
