### ISSUE TITLE
exsiting a 404 error

### ISSUE THREAD

**Issue by kllzheng** [tavyandy97/span-tree#44]
when I click a file, a 404 error will appear.
The reason is that additional '-/' is added in the URL corresponding to the file, as follows.
![image](https://user-images.githubusercontent.com/22348842/84340212-c2542e00-abd2-11ea-8f83-7737b7995d68.png)

**Comment by tavyandy97** [comment]
Hey @kllzheng 
I assume you are using a self hosted instance of GitLab (version <v13). 
Please refer to https://github.com/tavyandy97/span-tree/issues/37

**Comment by kllzheng** [comment]
> Hey @kllzheng
> I assume you are using a self hosted instance of GitLab (version <v13).
> Please refer to #37

**Comment by kllzheng** [comment]
When I enable the compatibility mode, it works. Thx！
