### ISSUE TITLE
error animation in certain webs

### ISSUE THREAD

**Issue by Nisgrak** [tavyandy97/span-tree#49]
Hi! 

If enter in some urls like below you see that some elements are randomly rotating:
- https://watracz.com/ (web itself)
- https://gocdkeys.com/en/search?product=red (the load more bar below)

Searching in the code the `.loader` class had the fault.

**Comment by tavyandy97** [comment]
Hey @Nisgrak !

The issue has been reproduced and we have started working on it. We will be releasing a fix soon.  

Thank You for the feedback and if you find SpanTree useful, do spread the word!

**Comment by tavyandy97** [comment]
Hey @Nisgrak !

The issue has been fixed. Thanks for the bug report. The update will be released on the Chrome Web Store and Mozilla Addons within a day.
