### ISSUE TITLE
Automatically show and hide on hover

### ISSUE THREAD

**Issue by ravicious** [tavyandy97/span-tree#50]
First of all, thanks for the extension, it makes browsing GitLab so much better.

For me, the one thing which would make the experience even better would be automatically showing and hiding the file tree on hover, like Octotree does. See the attached video (sorr for .tar.gz, but GitHub won't let me upload .mov straight away).

[octotree.mov.tar.gz](https://github.com/tavyandy97/span-tree/files/4971846/octotree.mov.tar.gz)

Not sure if you have time for that, but it'd be super cool for SpanTRee to have that.

**Comment by tavyandy97** [comment]
Hey @ravicious ! Happy to see that you like SpanTree.

I did consider the open on hover option while creating SpanTree. However, since GitLab already has a sidebar, it would have caused accidental opens of SpanTree while accessing the sidebar.

Thank You and do spread the word about SpanTree !

**Comment by ravicious** [comment]
Ah, that makes sense.
