### ISSUE TITLE
Why does it require permissions to all URLs?

### ISSUE THREAD

**Issue by ygordanniel** [tavyandy97/span-tree#52]
Hi folks. First of all, thank you very much for the extension, it really saved me a lot of time already. Amazing work!

With that said, I was wondering why the permissions is set to `all_urls` since the extension is specifically for Gitlab. Is there a specific reason for that?

Regards!

**Comment by tavyandy97** [comment]
Hey @ygordanniel ! Glad to see that you found the extension useful.

The reason that the extension requires permission to `all_urls` is that the extension also works on self-hosted instances of GitLab. 

Thank You and do spread the word about SpanTree !

**Comment by ygordanniel** [comment]
Got it. Thanks for the quick response. 

Keep it up with the amazing work!

**Comment by tavyandy97** [comment]
@ygordanniel You can use the workaround mentioned in https://github.com/tavyandy97/span-tree/issues/35 if you want to restrict the extension access

**Comment by ygordanniel** [comment]
Yeah, that exactly what I did. Thanks!
