### ISSUE TITLE
dont work on premise gitlab server 

### ISSUE THREAD

**Issue by erayerdem** [tavyandy97/span-tree#56]
we have out gitlab server . we can get succesfully all files in tree but when click  created url is broken 

https://gitlab.domain.com/xx/him/yy/-/blob/develop/Jenkinsfile

must be 

https://gitlab.domain.com/xx/him/yy/blob/develop/Jenkinsfile

**Comment by tavyandy97** [comment]
Hey @erayerdem ! Thank you for reporting the issue and hope you're finding SpanTree useful.

https://github.com/tavyandy97/span-tree/issues/37 This issue has been addressed. However, if switching on **_Compatibility Mode_** from the extension settings doesn't work, do let me know.

Do spread the word about SpanTree🌳

**Comment by erayerdem** [comment]
Hey @tavyandy97  ! thanks for your answer . its works  . good days
