### ISSUE TITLE
Banner color auto adapted GitLab themes

### ISSUE THREAD

**Issue by Zhiwei1996** [tavyandy97/span-tree#57]
SpanTree is a nice plugin, can it support auto change color adapt GitLab themes? Now only default purple

**Comment by tavyandy97** [comment]
Hey @Zhiwei1996 ! Hope you're finding SpanTree useful. 

Sorry for the late reply. Great Idea 💡 and can be looked into. Would you prefer it as an option in the extension popup menu? Or just that the extension always auto-detects the color?

Do spread the word about SpanTree!

**Comment by Zhiwei1996** [comment]
> Hey @Zhiwei1996 ! Hope you're finding SpanTree useful.
> 
> Sorry for the late reply. Great Idea 💡 and can be looked into. Would you prefer it as an option in the extension popup menu? Or just that the extension always auto-detects the color?
> 
> Do spread the word about SpanTree!

Option is better ;)

**Comment by tavyandy97** [comment]
I'll start working on it @Zhiwei1996 . Will keep you posted 👍

**Comment by tavyandy97** [comment]
https://github.com/tavyandy97/span-tree/pull/58

**Comment by tavyandy97** [comment]
Hey @Zhiwei1996 ! Sorry for the delay

The extension has been updated on the Chrome Webstore and Mozilla Addons to v0.0.4.0 with a fix for issue.


![image](https://user-images.githubusercontent.com/22865691/101777980-3c7d5500-3b19-11eb-8f93-dcea8ce0a391.png)

Please confirm and close the issue. Do spread the word about SpanTree!

**Comment by Zhiwei1996** [comment]
> Hey @Zhiwei1996 ! Sorry for the delay
> 
> The extension has been updated on the Chrome Webstore and Mozilla Addons to v0.0.4.0 with a fix for issue.
> 
> ![image](https://user-images.githubusercontent.com/22865691/101777980-3c7d5500-3b19-11eb-8f93-dcea8ce0a391.png)
> 
> Please confirm and close the issue. Do spread the word about SpanTree!

Thanks for your jobs, it's useful and nice plugin 👍
