### ISSUE TITLE
using minified code outside of NODE_ENV === "production"

### ISSUE THREAD

**Issue by aschaap** [tavyandy97/span-tree#64]
Thank you for the helpful extension! This error always shows up in the Javascript console, though it does not seem to affect the functionality. I'm using version 0.0.4.1.

**Comment by tavyandy97** [comment]
Hey @aschaap !

Glad to see that you found the extension useful. Please refer to the following [Issue](https://github.com/tavyandy97/span-tree/issues/34) regarding the problem that you have reported. Feel free to follow up if you have any more thoughts to share regarding the same.

Do spread the word about SpanTree !

**Comment by aschaap** [comment]
Hey @tavyandy97 , thank you for the link. It did not immediately stand out to me as the issue I noticed when perusing closed issues. I'll close this duplicate.
