### ISSUE TITLE
Which LICENSE  would you prefer?

### ISSUE THREAD

**Issue by xiongjiamu** [tavyandy97/span-tree#70]
Dear @tavyandy97 

Thanks for your work on this GitLab extension, I'm planning to use your Repo and do some personal modify to satisfy my own Repo.

Can I know which kind of you  Repo's LICENSE, Since you haven't add any LICENSE file yet?

Best wishes!

**Comment by tavyandy97** [comment]
Hey @xiongjiamu !

Just added an MIT license to the repository. Please feel free to modify and use the extension as per your usecase. 

If you think the extension could benefit from the changes you plan to make, do mention them here.

Thank you and do spread the word about SpanTree 🌳

**Comment by xiongjiamu** [comment]
Got it.

When we delivered our project, I would love to let you know, thx again.
