### ISSUE TITLE
Fix page reload upon file navigation

### ISSUE THREAD

**Issue by ArturBaybulatov** [tavyandy97/span-tree#79]
It would be great if a page wouldn't reload/refresh upon clicking/selecting a file in the SpanTree sidebar, and navigation were smoother. Right now the reload causes a whole page and the sidebar to redraw its layout triggering all the animations.

**Comment by tavyandy97** [comment]
Hey @ArturBaybulatov,  Hope you're finding SpanTree useful 🌳

Sorry for the late reply. While we were building SpanTree, we tried an iteration in which all the contents would be loaded and the page wouldn't be refreshed. However, in such an implementation a lot of features present in GitLab stopped working which would've been a deal breaker for a lot of users. Sadly we had to scratch the idea 😔

Closing this issue for now, but feel free to re-open it if you want to discuss things further.

Do spread the word about SpanTree!
