### ISSUE TITLE
Compatibility with GitLab Community Edition 15.3.1

### ISSUE THREAD

**Issue by avalou** [tavyandy97/span-tree#81]
Hi,

I daily use a Gitlab instane self hosted by the University I work at. We use GitLab CE [v15.3.1], and span-tree stopped to work with this version. The tab no longer appears on the side of the page.
Tested on 
* Firefox 104.0.1 (64-bit) (snap)
* Chromium 104.0.5112.101 (Official Build) snap (64-bit)

**Comment by tavyandy97** [comment]
Hey @avalou ,
Thanks a lot for reporting the issue. Have reproduced it the issue and am fixing it. Will update here as soon as the fix is out.

**Comment by tavyandy97** [comment]
Hey @avalou @edouard-lopez @PRGfx
Apologies for the delay. The extension has been updated on the Chrome Webstore to v0.0.4.4 with a fix for issue.

Thanks again for reporting the issue and do spread the word about SpanTree 🌳

**Comment by tavyandy97** [comment]
Haven't updated the Firefox extension since a year, since we've lost the credentials to the account.

**Comment by edouard-lopez** [comment]
Thanks for the news!
However, I'm also using Firefox :S

**Comment by avalou** [comment]
Is it really so hard to retrieve some credentials ? It really is annoying not to be able to use your extensions.

**Comment by edouard-lopez** [comment]
@tavyandy97 Did you try to reset your credentials or reach out to [Mozilla support for help](https://wiki.mozilla.org/Add-ons#Get_in_touch). You [don't seem to be the first to lost your credentials.](https://wiki.mozilla.org/Add-ons#Get_in_touch) :P
