### ISSUE TITLE
Feature: Customizable short key to activate

### ISSUE THREAD

**Issue by Braunson** [tavyandy97/span-tree#93]
CTRL + P is Print in Windows so that doesn't work to for anyone on Windows.

**Comment by tavyandy97** [comment]
Hey @Braunson ! Hope you're finding SpanTree useful.

Apologies for the late reply. Have made a fix to the extension and submitted it for review on the Chrome WebStore. Whenever `0.0.5.2` goes live you'll be able to use the extension with the fix.

Closing the issue for now, but feel free to re-open it in case it isn't fixed.

Do spread the word about SpanTree!
