### ISSUE TITLE
seems not work with gitlab 16

### ISSUE THREAD

**Issue by yurenchen000** [tavyandy97/span-tree#94]
//NOTE: gitlab version display need login

- https://gitlab.com/help
GitLab Enterprise Edition 16.10.0-pre [4e07bf86334](https://gitlab.com/gitlab-org/gitlab/-/commits/4e07bf86334)

- https://gitlab.gnome.org/help
GitLab Community Edition [v16.9.1](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v16.9.1)

**Comment by yurenchen000** [comment]
content.js:2970 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')

null !== document.querySelector("[data-qa-selector='branches_dropdown']").children[0])

> document.querySelector("[data-qa-selector='branches_dropdown']")
null

**Comment by tavyandy97** [comment]
@yurenchen000 I've deployed a patch, for the time being it's a hot fix. Have to do add some code to support the sidebar.
